[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:50 test_OrangeHRM_Login_002 is started
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:52 Opening the browser
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:57 Entering Username-->Admin
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:60 Entering Password-->admin123
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:63 Clicking on login button
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:65 Verifying the login status
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:67 test_OrangeHRM_Login_002 is passed
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:69 Taking the screenshot
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:71 Clicking on Menu button
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:73 Clicking on logout button
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:81 Closing the browser
[32mINFO    [0m Test_OrangeHRM_Login:test_OrangeHRM_Login.py:83 test_OrangeHRM_Login_002 is completed
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD14BCE060>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/efe7ca1d-addb-49fe-9a82-6a0857ca35a1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD14BCE390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/efe7ca1d-addb-49fe-9a82-6a0857ca35a1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD14BDA810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/efe7ca1d-addb-49fe-9a82-6a0857ca35a1